// Controller/verificationController.js
const db = require("../db/dbconnect");

// ----- QR decoder deps -----
// Make sure in Backend folder you ran:  npm install jimp qrcode-reader
let JimpLib = require("jimp");
const Jimp = JimpLib.Jimp || JimpLib; // compatible with old & new Jimp
const QrCode = require("qrcode-reader");

/* --- small promise helper (same style as in other controllers) --- */
function q(sql, params = []) {
  return new Promise((resolve, reject) => {
    db.query(sql, params, (err, rows) => (err ? reject(err) : resolve(rows)));
  });
}

/* --- helper to render a very simple HTML page (no React needed) --- */
function renderHtmlVerification(res, { ok, title, message, meta = {}, fileUrl = null }) {
  const safeTitle = title || (ok ? "Document Verified" : "Document Not Found");
  const statusColor = ok ? "#16a34a" : "#dc2626";

  const metaLines = Object.entries(meta)
    .filter(([_, v]) => v !== undefined && v !== null && v !== "")
    .map(
      ([k, v]) =>
        `<tr><td style="padding:4px 8px;font-weight:600;">${k}</td><td style="padding:4px 8px;">${v}</td></tr>`
    )
    .join("");

  const downloadBlock = fileUrl
    ? `<p style="margin-top:16px;">
         <a href="${fileUrl}" target="_blank"
            style="display:inline-block;padding:8px 14px;border-radius:6px;
                   background:#2563eb;color:#fff;text-decoration:none;font-weight:600;">
           View PDF Document
         </a>
       </p>`
    : "";

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>${safeTitle}</title>
</head>
<body style="font-family: system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif; background:#f3f4f6; margin:0; padding:24px;">
  <div style="max-width:640px;margin:0 auto;background:#fff;border-radius:12px;padding:24px;box-shadow:0 10px 30px rgba(15,23,42,0.12);">
    <h1 style="margin-top:0;font-size:22px;color:${statusColor};">${safeTitle}</h1>
    <p style="margin:8px 0 16px 0;font-size:14px;color:#111827;">${message}</p>

    ${metaLines
      ? `<table style="border-collapse:collapse;margin-top:8px;font-size:14px;">${metaLines}</table>`
      : ""}

    ${downloadBlock}

    <p style="margin-top:24px;font-size:11px;color:#6b7280;">
      This verification page is generated by the Municipal Permits System.
    </p>
  </div>
</body>
</html>`;

  res.status(ok ? 200 : 404).send(html);
}

/* ============================================================
   SHARED HELPERS FOR JSON + HTML
   ============================================================ */

const ALLOWED_TYPES = new Set(["business", "renewal_business", "special_sales"]);

async function loadIndexRow(app_uid) {
  const idxRows = await q(
    `SELECT app_uid, application_type, application_id, user_id, created_at
       FROM application_index
      WHERE app_uid = ?
      LIMIT 1`,
    [app_uid]
  );
  return idxRows[0] || null;
}

async function loadBusinessRow(appId) {
  const rows = await q(
    `SELECT BusinessP_id, business_name, trade_name, application_type, status, application_date
       FROM business_permits
      WHERE BusinessP_id = ?
      LIMIT 1`,
    [appId]
  );
  return rows[0] || null;
}

/**
 * Try to find a PDF attachment for this application.
 * labels = array in priority order.
 */
async function findAttachmentByLabels(app_uid, appType, appId, labels = []) {
  for (const label of labels) {
    const rows = await q(
      `SELECT pdf_path, uploaded_at
         FROM tbl_application_requirements
        WHERE app_uid = ?
          AND application_type = ?
          AND application_id = ?
          AND file_path = ?
        ORDER BY uploaded_at DESC
        LIMIT 1`,
      [app_uid, appType, appId, label]
    );
    if (rows[0] && rows[0].pdf_path) {
      return {
        label,
        pdf_path: rows[0].pdf_path,
        uploaded_at: rows[0].uploaded_at,
      };
    }
  }
  return null;
}

/* ============================================================
   1) HTML: Verify Business Permit LGU Form (with assessment)
   QR encodes something like:
     http://host/api/verification/app/APP-...
   OR older:
     http://host/api/verify/app/APP-...
   ============================================================ */

exports.verifyBusinessApplication = async (req, res) => {
  const { app_uid } = req.params || {};
  if (!app_uid) {
    return renderHtmlVerification(res, {
      ok: false,
      title: "Invalid QR",
      message: "Missing application UID in URL.",
    });
  }

  try {
    const idx = await loadIndexRow(app_uid);
    if (!idx) {
      return renderHtmlVerification(res, {
        ok: false,
        title: "Document Not Found",
        message: "No application is registered for this QR code.",
      });
    }

    const appType = String(idx.application_type || "").toLowerCase();
    const appId = idx.application_id;

    if (!ALLOWED_TYPES.has(appType)) {
      return renderHtmlVerification(res, {
        ok: false,
        title: "Unsupported Application Type",
        message: `This QR refers to application type "${appType}", which is not yet supported by the verifier.`,
        meta: {
          "Application Type": appType,
          "Application ID": appId,
        },
      });
    }

    const biz = await loadBusinessRow(appId);
    if (!biz) {
      return renderHtmlVerification(res, {
        ok: false,
        title: "Document Not Found",
        message: "Business permit application was not found in the system.",
        meta: {
          "Application Type": appType,
          "Application ID": appId,
        },
      });
    }

    const fileLabel = "Business Permit LGU Form";
    const attach = await findAttachmentByLabels(app_uid, appType, appId, [fileLabel]);

    if (!attach) {
      return renderHtmlVerification(res, {
        ok: false,
        title: "Document Not Found",
        message:
          "This application exists, but the LGU-form PDF attached for this QR could not be located.",
        meta: {
          "Application Type": appType,
          "Application ID": appId,
          Status: biz.status || "Unknown",
        },
      });
    }

    const base = `${req.protocol}://${req.get("host")}`;
    const fileUrl = `${base}${attach.pdf_path}`;

    return renderHtmlVerification(res, {
      ok: true,
      title: "Business Permit Document Verified",
      message:
        "This QR code matches a valid Business Permit LGU Form in the Municipal Permits System.",
      meta: {
        "Application UID": app_uid,
        "Application Type": appType,
        "Application ID": appId,
        "Business Name": biz.business_name || biz.trade_name || "N/A",
        Status: biz.status || "Unknown",
        "Application Date": biz.application_date
          ? new Date(biz.application_date).toLocaleDateString()
          : "N/A",
      },
      fileUrl,
    });
  } catch (e) {
    console.error("verifyBusinessApplication error:", e);
    return renderHtmlVerification(res, {
      ok: false,
      title: "Server Error",
      message: "An internal error occurred while verifying this document.",
    });
  }
};

/* ============================================================
   2) HTML: Verify Mayor's Permit Final Output
   QR encodes something like:
     http://host/api/verification/mayors/APP-...
   OR older:
     http://host/api/verify/mayors/APP-...
   ============================================================ */

exports.verifyMayorsPermit = async (req, res) => {
  const { app_uid } = req.params || {};
  if (!app_uid) {
    return renderHtmlVerification(res, {
      ok: false,
      title: "Invalid QR",
      message: "Missing application UID in URL.",
    });
  }

  try {
    const idx = await loadIndexRow(app_uid);
    if (!idx) {
      return renderHtmlVerification(res, {
        ok: false,
        title: "Document Not Found",
        message: "No application is registered for this QR code.",
      });
    }

    const appType = String(idx.application_type || "").toLowerCase();
    const appId = idx.application_id;

    const allowedTypes = new Set(["business", "renewal_business"]);
    if (!allowedTypes.has(appType)) {
      return renderHtmlVerification(res, {
        ok: false,
        title: "Unsupported Application Type",
        message: `This QR refers to application type "${appType}", which is not mapped to a Mayor's Permit document.`,
        meta: {
          "Application Type": appType,
          "Application ID": appId,
        },
      });
    }

    const biz = await loadBusinessRow(appId);
    if (!biz) {
      return renderHtmlVerification(res, {
        ok: false,
        title: "Document Not Found",
        message: "Business permit application was not found in the system.",
        meta: {
          "Application Type": appType,
          "Application ID": appId,
        },
      });
    }

    const label = "Mayor’s Permit – Final Output"; // EXACT same string used in upsertAttachment
    const attach = await findAttachmentByLabels(app_uid, appType, appId, [label]);

    if (!attach) {
      return renderHtmlVerification(res, {
        ok: false,
        title: "Document Not Found",
        message:
          "This application exists, but the Mayor’s Permit PDF for this QR could not be located.",
        meta: {
          "Application Type": appType,
          "Application ID": appId,
          Status: biz.status || "Unknown",
        },
      });
    }

    const base = `${req.protocol}://${req.get("host")}`;
    const fileUrl = `${base}${attach.pdf_path}`;

    return renderHtmlVerification(res, {
      ok: true,
      title: "Mayor’s Permit Verified",
      message:
        "This QR code matches a valid Mayor’s Permit document in the Municipal Permits System.",
      meta: {
        "Application UID": app_uid,
        "Application Type": appType,
        "Application ID": appId,
        "Business Name": biz.business_name || biz.trade_name || "N/A",
        Status: biz.status || "Unknown",
        "Application Date": biz.application_date
          ? new Date(biz.application_date).toLocaleDateString()
          : "N/A",
      },
      fileUrl,
    });
  } catch (e) {
    console.error("verifyMayorsPermit error:", e);
    return renderHtmlVerification(res, {
      ok: false,
      title: "Server Error",
      message: "An internal error occurred while verifying this document.",
    });
  }
};

/* ============================================================
   3) JSON: unified verifier (NO document type selection)
      /api/verification/any-json/:app_uid
      Chooses: Mayor's final > Business LGU form
   ============================================================ */

/* ============================================================
   3) JSON: unified verifier (NO manual document type selection)
      /api/verification/any-json/:app_uid?prefer=business_lgu_form|mayors_permit
   ============================================================ */

exports.verifyAnyJson = async (req, res) => {
  const { app_uid } = req.params || {};
  const prefer = (req.query.prefer || "").toLowerCase(); // <-- hint from QR

  if (!app_uid) {
    return res.status(400).json({
      success: false,
      message: "Missing application UID.",
    });
  }

  try {
    const idx = await loadIndexRow(app_uid);
    if (!idx) {
      return res.status(404).json({
        success: false,
        message: "No application is registered for this UID.",
      });
    }

    const appType = String(idx.application_type || "").toLowerCase();
    const appId = idx.application_id;

    if (!ALLOWED_TYPES.has(appType)) {
      return res.status(400).json({
        success: false,
        message: `Application type "${appType}" is not supported for verification.`,
      });
    }

    const biz = await loadBusinessRow(appId);
    if (!biz) {
      return res.status(404).json({
        success: false,
        message: "Business permit application was not found in the system.",
      });
    }

    const LABEL_MAYOR = "Mayor’s Permit – Final Output";
    const LABEL_LGU = "Business Permit LGU Form";

    // ----- decide search order based on 'prefer' hint -----
    let labelOrder;
    if (
      prefer === "mayors_permit" ||
      prefer === "mayor" ||
      prefer === "mayors"
    ) {
      // QR came from Mayor's permit page → check Mayor first
      labelOrder = [LABEL_MAYOR, LABEL_LGU];
    } else if (
      prefer === "business_lgu_form" ||
      prefer === "business_permit" ||
      prefer === "business" ||
      prefer === "lgu"
    ) {
      // QR came from LGU form page → check LGU first
      labelOrder = [LABEL_LGU, LABEL_MAYOR];
    } else {
      // No hint (typed UID) → default: Mayor > LGU
      labelOrder = [LABEL_MAYOR, LABEL_LGU];
    }

    const attach = await findAttachmentByLabels(
      app_uid,
      appType,
      appId,
      labelOrder
    );

    if (!attach) {
      return res.status(404).json({
        success: false,
        message:
          "This application exists, but no known permit document (Mayor's or LGU Form) was found.",
      });
    }

    const base = `${req.protocol}://${req.get("host")}`;
    const fileUrl = `${base}${attach.pdf_path}`;

    let docKind = "unknown";
    if (attach.label === LABEL_MAYOR) docKind = "mayors_permit";
    else if (attach.label === LABEL_LGU) docKind = "business_lgu_form";

    return res.json({
      success: true,
      message: "Permit document verified.",
      doc_kind: docKind,
      app_uid,
      application_type: appType,
      application_id: appId,
      file_url: fileUrl,
      label: attach.label,
      meta: {
        business_name: biz.business_name || biz.trade_name || "N/A",
        status: biz.status || "Unknown",
        application_date: biz.application_date
          ? new Date(biz.application_date).toISOString()
          : null,
      },
    });
  } catch (e) {
    console.error("verifyAnyJson error:", e);
    return res.status(500).json({
      success: false,
      message: "Server error while verifying document.",
    });
  }
};


/* ============================================================
   4) QR image upload: decode and extract app_uid
      /api/verification/upload-qr   (POST, multipart/form-data)
      field name:  qr
   ============================================================ */

exports.decodeQrFromImage = async (req, res) => {
  try {
    const file = req.files?.qr;
    if (!file) {
      return res.status(400).json({
        success: false,
        message: "No QR image uploaded. Please choose an image file.",
      });
    }

    // Read image buffer using Jimp
    const image = await Jimp.read(file.data); // <-- this is where Jimp.read must exist
    const qr = new QrCode();

    const decodedText = await new Promise((resolve, reject) => {
      qr.callback = (err, value) => {
        if (err) return reject(err);
        resolve(value && value.result ? String(value.result) : "");
      };
      qr.decode(image.bitmap);
    });

    if (!decodedText) {
      return res.status(400).json({
        success: false,
        message: "Unable to read a QR code from this image.",
      });
    }

    const raw = decodedText.trim();
    let app_uid = null;
    let doc_hint = null;

    // Accept MANY possible URL shapes:
    //  - /api/verification/app/APP-...
    //  - /verification/app/APP-...
    //  - /api/verify/app/APP-...
    //  - /verify/app/APP-...
    //  - and same for /mayors/...
    const urlMatch = raw.match(
      /(?:\/api)?\/(?:verification|verify)\/(app|mayors)\/([^/?#]+)/i
    );

    if (urlMatch) {
      const kind = urlMatch[1].toLowerCase(); // "app" or "mayors"
      app_uid = urlMatch[2];
      if (kind === "app") doc_hint = "business_lgu_form";
      if (kind === "mayors") doc_hint = "mayors_permit";
    } else if (/^APP-/i.test(raw)) {
      // QR contains just the UID text
      app_uid = raw;
    }

    if (!app_uid) {
      return res.status(400).json({
        success: false,
        message:
          "No valid Application UID was found in the QR-Code or Permits are n.",
        raw_text: raw,
      });
    }

    // We do NOT force doc type here; verifyAnyJson will choose Mayor > LGU
    return res.json({
      success: true,
      message: "QR decoded successfully.",
      app_uid,
      doc_hint,
      raw_text: raw,
    });
  } catch (e) {
    console.error("decodeQrFromImage error:", e);
    return res.status(500).json({
      success: false,
      message: "Server error while decoding QR image.",
    });
  }
};
